### ISSUE TITLE
Multi-line title for the link

### ISSUE THREAD

**Issue by feigaoxyz** [RobTrew/copy-as-md-link#2]
Some applications (i.e. Things, Calendar) may return multi-line text for the title. But it won't be good for 
Suggest to either to only keep the first line or join the lines together.

Example:
* Things
```
[task name

note line 1
note line 2](things:///show?id=xxxx)
```

**Comment by RobTrew** [comment]
> But it won't be good for
?

Not sure that I have followed that part, but single-line label text does sound sensible.

I'll take a look in a few days.

**Comment by RobTrew** [comment]
Each app-specific module returns a whole `[label](url)` link, so the trick might be to track down the offenders (e.g. Things), and use some kind of `firstLineOnly` function upstream – in the app-specific code.

Possibly something like:
```javascript
(() => {
    "use strict";

    // firstNonEmptyLineIfAny :: String -> String
    const firstNonEmptyLineIfAny = s => {
        // Either an empty string, or the first
        // non-empty line in s, if there is one.
        const
            xs = s.split(/\r\n|\n|\r/u),
            i = xs.findIndex(x => Boolean(x.trim()));

        return -1 !== i ? (
            xs[i]
        ) : "";
    };

    // ---------------------- TEST -----------------------
    return JSON.stringify(
        [
            "",
            "label",
            "\n\nlabel\n",
            "label\nrest\netc"
        ].map(firstNonEmptyLineIfAny)
    );
})();
```

**Comment by feigaoxyz** [comment]
sorry my typo.

Thanks for the `firstNonEmptyLineIfAny`, I will put it in app-specific code for the offenders.

However, for Things, the macro used the native menu item ("Copy Text"), so I am running a shell snippet to process the clipboard.

<img width="723" alt="CleanShot-20220729140242-KHsLncu0" src="https://user-images.githubusercontent.com/5907519/181693202-5cd877c8-5060-4c9b-8399-8426678d20a1.png">
