### ISSUE TITLE
Reeder 5 has no title for the link

### ISSUE THREAD

**Issue by feigaoxyz** [RobTrew/copy-as-md-link#3]
The MD link from Reeder 5 has no text for the title, is this the expected behaviour?
```javascript
    const main = () =>
        either(alert('Reeder link'))(x => x)(
            bindLR(
                clipOfTypeLR('public.utf8-plain-text')
            )(link => Right(`[](${link})`))
        );
```

**Comment by RobTrew** [comment]
That's expected – Reeder 5 provides no mechanism that I can see for copying the name of an item.

(If you do find one, let me know, and I can try to incorporate it)

**Comment by feigaoxyz** [comment]
noted. thanks.
